name: build-docs
run-name: ${{ github.actor }} ${{ github.event_name }} to ${{ github.base_ref }} 
on:
   push:
    tags:
      - 'v*'
jobs:
  build_doxygen:
    uses: EddyTheCo/Common/.github/workflows/build-docs.yml@v0.1.1
    permissions:
      pages: write
      id-token: write
